## 💻 Laptop Price Prediction - using Linear Regression model

### 🎯 Objectives:
The goal of this exercise is to apply `Linear Regression` to predict laptop price based on available features.  
We will:
- Import and read the dataset
- Check for missing values 
- Train a linear regression model
- Calculate the mean squared error (MSE)
- Build a baseline model
- Visualize the predictions to evaluate the model performance

### Import Libraries

In [1]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

### 🗂️ Data Preparation

In [11]:
#import kagglehub

# Download latest version
#path = kagglehub.dataset_download("gyanprakashkushwaha/laptop-price-prediction-cleaned-dataset")

#print("Path to dataset files:", path)

In [4]:
# 1. Load dataset
df = pd.read_csv('laptop_data_cleaned.csv')
df.head()

,Company,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os
0,Apple,Ultrabook,8,1.37,11.175755,0,1,226.983005,Intel Core i5,0,128,Intel,Mac
1,Apple,Ultrabook,8,1.34,10.776777,0,0,127.677940,Intel Core i5,0,0,Intel,Mac
2,HP,Notebook,8,1.86,10.329931,0,0,141.211998,Intel Core i5,0,256,Intel,Others
3,Apple,Ultrabook,16,1.83,11.814476,0,1,220.534624,Intel Core i7,0,512,AMD,Mac
4,Apple,Ultrabook,8,1.37,11.473101,0,1,226.983005,Intel Core i5,0,256,Intel,Mac

🧹 Check for missing values and handle them using the dropna() function.

In [5]:
# Check for missing values

# Drop rows with missing values (if any)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1273 entries, 0 to 1272
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Company      1273 non-null   object
 1   TypeName     1273 non-null   object
 2   Ram          1273 non-null   int64
 3   Weight       1273 non-null   float64
 4   Price        1273 non-null   float64
 5   TouchScreen  1273 non-null   int64
 6   Ips          1273 non-null   int64
 7   Ppi          1273 non-null   float64
 8   Cpu_brand    1273 non-null   object
 9   HDD          1273 non-null   int64
 10  SSD          1273 non-null   int64
 11  Gpu_brand    1273 non-null   object
 12  Os           1273 non-null   object
dtypes: float64(3), int64(5), object(5)
memory usage: 129.4+ KB

In [7]:
# Run this cell to encode all categorical columns using one-hot encoding
cat_cols = df.select_dtypes(include='object').columns
df = pd.get_dummies(df, columns=cat_cols, drop_first=True) 

df.head()

,Ram,Weight,Price,TouchScreen,Ips,Ppi,HDD,SSD,Company_Apple,Company_Asus,...,TypeName_Ultrabook,TypeName_Workstation,Cpu_brand_Intel Core i3,Cpu_brand_Intel Core i5,Cpu_brand_Intel Core i7,Cpu_brand_Other Intel Processor,Gpu_brand_Intel,Gpu_brand_Nvidia,Os_Others,Os_Windows
0,8,1.37,11.175755,0,1,226.983005,0,128,True,False,...,True,False,False,True,False,False,True,False,False,False
1,8,1.34,10.776777,0,0,127.677940,0,0,True,False,...,True,False,False,True,False,False,True,False,False,False
2,8,1.86,10.329931,0,0,141.211998,0,256,False,False,...,False,False,False,True,False,False,True,False,True,False
3,16,1.83,11.814476,0,1,220.534624,0,512,True,False,...,True,False,False,False,True,False,False,False,False,False
4,8,1.37,11.473101,0,1,226.983005,0,256,True,False,...,True,False,False,True,False,False,True,False,False,False

### 🤖 Build Linear Regression Model - Predicting Laptop Price

In this exercise, `Price` is selected as the target variable we aim to predict.

In [8]:
# 1. Split the features and the target (Target: 'Price')

# 2. Split the data into training and test sets

# 3. Create a Linear Regression model

# 4. Fit the model to the training data

# 5. Predict the scores using the test data

# 6. Calculate and print the Mean Squared Error (MSE)

### ⚙️ Build Baseline Model

In [9]:
# 1. Create a baseline predection model

# 2. Calculate and print the baseline MES

### 📉 Visualization

In [10]:
# 1. Create the figure and set its size

# 2. Plot a scatter plot of actual vs predicted values

# 3. Draw a dashed line from min to max as a reference

# 4. Label the x-axis and y-axis

# 5. Add a title to the plot

# 6. Add a grid

# 7. Show the plot